CREATE OR REPLACE STREAM "mc_status" (CORRELATION_ID STRING, ERROR_CODE STRING)
  WITH (kafka_topic='mvp.public.mc_status', partitions=1, key_format='KAFKA', value_format='JSON');

CREATE OR REPLACE STREAM "mc_payments" (BFO_TRANSACTION_ID STRING, CORRELATION_ID STRING, SOURCE_ACCOUNT STRING, SOURCE_ACCOUNT_CURRENCY STRING, SOURCE_ACCOUNT_OWNERID STRING, TARGET_ACCOUNT STRING, TARGET_ACCOUNT_CURRENCY STRING, TARGET_ACCOUNT_OWNERID STRING, TARGET_ACCOUNT_OWNER_NAME STRING, TRANSACTION_AMOUNT STRING, TRANSACTION_CURRENCY STRING, TRANSACTION_DESCRIPTION STRING, TRANSACTION_TYPE STRING, TRANSACTION_VALUEDATE DATE)
  WITH (kafka_topic='mvp.public.mc_payments', partitions=1, key_format='KAFKA', value_format='JSON');

CREATE OR REPLACE STREAM "transactions"
  WITH (kafka_topic='transactions', partitions=1)
  AS SELECT 'D' AS CREDIT_DEBIT, 'IBT' AS TYPE_GROUP, P.BFO_TRANSACTION_ID AS TRANSACTION_ID, P.CORRELATION_ID AS CORRELATION_ID, P.SOURCE_ACCOUNT AS SOURCE_ACCOUNT, P.SOURCE_ACCOUNT_OWNERID AS CUSTOMER_ID, P.TARGET_ACCOUNT AS DESTINATION_ACCOUNT, P.TRANSACTION_AMOUNT AS AMOUNT, P.TRANSACTION_CURRENCY AS TRANSACTION_CURRENCY, P.TRANSACTION_DESCRIPTION AS DESCRIPTION, P.TRANSACTION_TYPE AS TYPE, P.TRANSACTION_VALUEDATE AS BOOKING_DATE, T.ERROR_CODE AS STATUS FROM "mc_status" T INNER JOIN "mc_payments" P
    WITHIN 365 DAYS GRACE PERIOD 365 DAYS
  ON T.CORRELATION_ID = P.CORRELATION_ID;

CREATE OR REPLACE STREAM "trans_status_init"
  WITH (kafka_topic='trans_status_init', partitions=1)
  AS SELECT * FROM "transactions" WHERE (STATUS = '0000');

CREATE OR REPLACE STREAM "trans_status_ok"
  WITH (kafka_topic='trans_status_ok', partitions=1)
  AS SELECT * FROM "transactions" WHERE (STATUS = '0001');