name: Add transactions on AWS
run-name: Add transactions on AWS (triggered by @${{ github.actor }})
on: workflow_dispatch

jobs:
  add-aws-transactions:
    uses: ./.github/workflows/add_transactions.yml
    secrets:
      database-host: ${{ secrets.AWS_DATABASE_HOST }}
      database-name: ${{ secrets.AWS_DATABASE_NAME }}
      database-username: ${{ secrets.AWS_DATABASE_USERNAME }}
      database-password: ${{ secrets.AWS_DATABASE_PASSWORD }}
      database-port: ${{ secrets.AWS_DATABASE_PORT }}
